name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ["jupyterlab-pytorch-cuda"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Dectect file changes
        id: changes
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            dockerfile:
              - ./${{matrix.containers}}/meta.yaml

      - name: Read file meta.yaml
        id: meta
        uses: mikefarah/yq@master
        with:
          cmd: yq '"ninthkat/${{matrix.containers}}:" + .tags[] + ","' ${{ matrix.containers}}/meta.yaml

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        if: steps.changes.outputs.dockerfile_any_changed == 'true'
        with:
          context: ${{ matrix.containers}}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.result}}
