name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ["jupyterlab-pytorch-cuda"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Aliyun container registry
        uses: docker/login-action@v3
        with: 
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Dectect file changes
        id: changes
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            dockerfile:
              - ./${{matrix.containers}}/meta.yaml

      - name: Read file meta.yaml
        id: meta
        uses: mikefarah/yq@master
        with:
          cmd: yq '. as $r | .images[] | . + ":" + $r.tags[] + ","' ${{ matrix.containers}}/meta.yaml

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        if: steps.changes.outputs.dockerfile_any_changed == 'true'
        with:
          context: ${{ matrix.containers}}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.result}}
